import Head from "next/head";

import Header from "./Header";

const Layout = ({ children }: { children: React.ReactNode }) => {

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main>
                {children}
            </main>
        </>
    )
};

export default Layout;